name: Setup JFrog CLI Example
'on':
  push:
    branches:
      - '*'
jobs:
  auth:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - name: Checkout
        uses: actions/checkout@v3
              
      - name: Setup Node npm
        uses: actions/setup-node@v3
      
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4.5.6
        env:
          JF_URL: https://idani.jfrog.io
        with:
          oidc-provider-name: amitl
          oidc-audience: amitl
      - name: Set CLI Config
        run: jf npm-config --global=true --repo-resolve=amitl-npm --repo-deploy=amitl-npm
           
      - name: Install Dependencies
        run: jf npm install
        
      - name: JF | XRay Scan Files
        run: | 
         jf scan . --recursive --extended-table=true --format=sarif --fail=${{ inputs.JFROG_FAIL_ON_SCAN }} > jfrog_scan.sarif
         ls -ll

      - name: JF | XRay Security Audit (SCA, SAST, Secrets)
        run: | 
         jf audit --sca --sast --secrets --extended-table -
         ls -ll
           
         
      - name: Publish
        run: jf npm publish
         
      - name: Publish Build info With JFrog CLI
        run: |
         # Collect environment variables for the build
         jf rt build-collect-env
         # Collect VCS details from git and add them to the build
         jf rt build-add-git
         # scan build
         jf scan build
         # Publish build info
         jf rt build-publish
