
name: Setup JFrog CLI Example
on: push

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write
jobs:
  auth:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - name: Checkout
        uses: actions/checkout@v3
              
      - name: Setup Node npm
        uses: actions/setup-node@v3
      
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4.5.6
        env:
          JF_URL: https://idani.jfrog.io
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JFROG_CLI_LOG_LEVEL: DEBUG

        with:
          oidc-provider-name: amitl
          oidc-audience: amitl
      - name: Set CLI Config
        run: jf npm-config --global=true --repo-resolve=amitl-npm --repo-deploy=amitl-npm
           
      - name: Install Dependencies
        run: jf npm install  

      - name: JF | XRay Scan Files
        run: | 
         jf scan . --recursive
         ls -ll
      - name: JF | XRay Scan Files
        run: | 
         docker login -uamitl idani.jfrog.io  --password 'Password12!@1'
         docker pull flask-app:latest
         jf docker scan flask-app:latest


